/* SPDX-License-Identifier: Apache-2.0 */
/* GENERATED by tools/art (npm run art). Do not edit.
 * Geometry: OpenMausBot (Apache-2.0); see tools/art/source/README.md. */
#include "maus_art.h"

extern const lv_image_dsc_t maus_s150_body;
extern const lv_image_dsc_t maus_s150_eye_0_0;
extern const lv_image_dsc_t maus_s150_eye_0_1;
extern const lv_image_dsc_t maus_s150_eye_0_2;
extern const lv_image_dsc_t maus_s150_eye_0_3;
extern const lv_image_dsc_t maus_s150_eye_1_0;
extern const lv_image_dsc_t maus_s150_eye_1_1;
extern const lv_image_dsc_t maus_s150_eye_1_2;
extern const lv_image_dsc_t maus_s150_eye_1_3;
extern const lv_image_dsc_t maus_s150_eye_3_0;
extern const lv_image_dsc_t maus_s150_eye_3_1;
extern const lv_image_dsc_t maus_s150_eye_3_2;
extern const lv_image_dsc_t maus_s150_eye_3_3;
extern const lv_image_dsc_t maus_s150_eye_4_0;
extern const lv_image_dsc_t maus_s150_eye_4_1;
extern const lv_image_dsc_t maus_s150_eye_4_2;
extern const lv_image_dsc_t maus_s150_eye_4_3;
extern const lv_image_dsc_t maus_s150_eye_5_0;
extern const lv_image_dsc_t maus_s150_eye_5_1;
extern const lv_image_dsc_t maus_s150_eye_5_2;
extern const lv_image_dsc_t maus_s150_eye_5_3;
extern const lv_image_dsc_t maus_s150_eye_6_0;
extern const lv_image_dsc_t maus_s150_eye_6_1;
extern const lv_image_dsc_t maus_s150_eye_6_2;
extern const lv_image_dsc_t maus_s150_eye_6_3;
extern const lv_image_dsc_t maus_s150_eye_7_0;
extern const lv_image_dsc_t maus_s150_eye_7_1;
extern const lv_image_dsc_t maus_s150_eye_7_2;
extern const lv_image_dsc_t maus_s150_eye_7_3;
extern const lv_image_dsc_t maus_s150_eye_8_0;
extern const lv_image_dsc_t maus_s150_eye_8_1;
extern const lv_image_dsc_t maus_s150_eye_8_2;
extern const lv_image_dsc_t maus_s150_eye_8_3;
extern const lv_image_dsc_t maus_s150_eye_10_0;
extern const lv_image_dsc_t maus_s150_eye_10_1;
extern const lv_image_dsc_t maus_s150_eye_10_2;
extern const lv_image_dsc_t maus_s150_eye_10_3;
extern const lv_image_dsc_t maus_s150_eye_11_0;
extern const lv_image_dsc_t maus_s150_eye_11_1;
extern const lv_image_dsc_t maus_s150_eye_11_2;
extern const lv_image_dsc_t maus_s150_eye_11_3;
extern const lv_image_dsc_t maus_s150_eye_13_0;
extern const lv_image_dsc_t maus_s150_eye_13_1;
extern const lv_image_dsc_t maus_s150_eye_13_2;
extern const lv_image_dsc_t maus_s150_eye_13_3;
extern const lv_image_dsc_t maus_s150_eye_14_0;
extern const lv_image_dsc_t maus_s150_eye_14_1;
extern const lv_image_dsc_t maus_s150_eye_14_2;
extern const lv_image_dsc_t maus_s150_eye_14_3;
extern const lv_image_dsc_t maus_s150_eye_15_0;
extern const lv_image_dsc_t maus_s150_eye_15_1;
extern const lv_image_dsc_t maus_s150_eye_15_2;
extern const lv_image_dsc_t maus_s150_eye_15_3;
extern const lv_image_dsc_t maus_s150_eye_16_0;
extern const lv_image_dsc_t maus_s150_eye_16_1;
extern const lv_image_dsc_t maus_s150_eye_16_2;
extern const lv_image_dsc_t maus_s150_eye_16_3;
extern const lv_image_dsc_t maus_s150_eye_17_0;
extern const lv_image_dsc_t maus_s150_eye_17_1;
extern const lv_image_dsc_t maus_s150_eye_17_2;
extern const lv_image_dsc_t maus_s150_eye_17_3;
extern const lv_image_dsc_t maus_s150_eye_19_0;
extern const lv_image_dsc_t maus_s150_eye_19_1;
extern const lv_image_dsc_t maus_s150_eye_19_2;
extern const lv_image_dsc_t maus_s150_eye_19_3;
extern const lv_image_dsc_t maus_s150_eye_21_0;
extern const lv_image_dsc_t maus_s150_eye_21_1;
extern const lv_image_dsc_t maus_s150_eye_21_2;
extern const lv_image_dsc_t maus_s150_eye_21_3;
extern const lv_image_dsc_t maus_s150_eye_22_0;
extern const lv_image_dsc_t maus_s150_eye_22_1;
extern const lv_image_dsc_t maus_s150_eye_22_2;
extern const lv_image_dsc_t maus_s150_eye_22_3;
extern const lv_image_dsc_t maus_s150_mouth_0;
extern const lv_image_dsc_t maus_s150_mouth_1;
extern const lv_image_dsc_t maus_s150_mouth_3;
extern const lv_image_dsc_t maus_s150_mouth_4;
extern const lv_image_dsc_t maus_s150_mouth_5;
extern const lv_image_dsc_t maus_s150_mouth_6;
extern const lv_image_dsc_t maus_s150_mouth_7;
extern const lv_image_dsc_t maus_s150_mouth_8;
extern const lv_image_dsc_t maus_s150_mouth_10;
extern const lv_image_dsc_t maus_s150_mouth_11;
extern const lv_image_dsc_t maus_s150_mouth_13;
extern const lv_image_dsc_t maus_s150_mouth_14;
extern const lv_image_dsc_t maus_s150_mouth_15;
extern const lv_image_dsc_t maus_s150_mouth_16;
extern const lv_image_dsc_t maus_s150_mouth_17;
extern const lv_image_dsc_t maus_s150_mouth_19;
extern const lv_image_dsc_t maus_s150_mouth_21;
extern const lv_image_dsc_t maus_s150_mouth_22;
extern const lv_image_dsc_t maus_s150_speak_19_1;
extern const lv_image_dsc_t maus_s150_speak_19_2;
extern const lv_image_dsc_t maus_s150_speak_19_3;
extern const lv_image_dsc_t maus_s150_speak_6_1;
extern const lv_image_dsc_t maus_s150_speak_6_2;
extern const lv_image_dsc_t maus_s150_speak_6_3;

static const uint8_t expr_ids[MAUS_EXPR_COUNT] = {0, 1, 3, 4, 5, 6, 7, 8, 10, 11, 13, 14, 15, 16, 17, 19, 21, 22};

static const maus_layer_t eyes[MAUS_EXPR_COUNT][MAUS_BLINK_STEPS] = {
  {{&maus_s150_eye_0_0, 22, 57}, {&maus_s150_eye_0_1, 22, 61}, {&maus_s150_eye_0_2, 22, 64}, {&maus_s150_eye_0_3, 23, 67}},
  {{&maus_s150_eye_1_0, 20, 51}, {&maus_s150_eye_1_1, 20, 57}, {&maus_s150_eye_1_2, 20, 63}, {&maus_s150_eye_1_3, 20, 66}},
  {{&maus_s150_eye_3_0, 14, 50}, {&maus_s150_eye_3_1, 14, 56}, {&maus_s150_eye_3_2, 14, 61}, {&maus_s150_eye_3_3, 14, 64}},
  {{&maus_s150_eye_4_0, 13, 60}, {&maus_s150_eye_4_1, 13, 63}, {&maus_s150_eye_4_2, 13, 65}, {&maus_s150_eye_4_3, 13, 66}},
  {{&maus_s150_eye_5_0, 18, 57}, {&maus_s150_eye_5_1, 18, 63}, {&maus_s150_eye_5_2, 18, 65}, {&maus_s150_eye_5_3, 18, 66}},
  {{&maus_s150_eye_6_0, 23, 57}, {&maus_s150_eye_6_1, 23, 61}, {&maus_s150_eye_6_2, 23, 65}, {&maus_s150_eye_6_3, 23, 67}},
  {{&maus_s150_eye_7_0, 17, 53}, {&maus_s150_eye_7_1, 17, 59}, {&maus_s150_eye_7_2, 17, 64}, {&maus_s150_eye_7_3, 17, 67}},
  {{&maus_s150_eye_8_0, 20, 54}, {&maus_s150_eye_8_1, 20, 59}, {&maus_s150_eye_8_2, 20, 63}, {&maus_s150_eye_8_3, 20, 65}},
  {{&maus_s150_eye_10_0, 20, 50}, {&maus_s150_eye_10_1, 20, 56}, {&maus_s150_eye_10_2, 20, 62}, {&maus_s150_eye_10_3, 20, 65}},
  {{&maus_s150_eye_11_0, 15, 41}, {&maus_s150_eye_11_1, 15, 50}, {&maus_s150_eye_11_2, 15, 59}, {&maus_s150_eye_11_3, 15, 64}},
  {{&maus_s150_eye_13_0, 14, 60}, {&maus_s150_eye_13_1, 14, 63}, {&maus_s150_eye_13_2, 14, 65}, {&maus_s150_eye_13_3, 14, 66}},
  {{&maus_s150_eye_14_0, 19, 50}, {&maus_s150_eye_14_1, 19, 56}, {&maus_s150_eye_14_2, 19, 62}, {&maus_s150_eye_14_3, 19, 66}},
  {{&maus_s150_eye_15_0, 27, 58}, {&maus_s150_eye_15_1, 27, 62}, {&maus_s150_eye_15_2, 27, 65}, {&maus_s150_eye_15_3, 27, 67}},
  {{&maus_s150_eye_16_0, 23, 50}, {&maus_s150_eye_16_1, 23, 56}, {&maus_s150_eye_16_2, 23, 61}, {&maus_s150_eye_16_3, 23, 65}},
  {{&maus_s150_eye_17_0, 21, 54}, {&maus_s150_eye_17_1, 21, 59}, {&maus_s150_eye_17_2, 21, 63}, {&maus_s150_eye_17_3, 21, 66}},
  {{&maus_s150_eye_19_0, 21, 51}, {&maus_s150_eye_19_1, 21, 57}, {&maus_s150_eye_19_2, 21, 63}, {&maus_s150_eye_19_3, 21, 66}},
  {{&maus_s150_eye_21_0, 12, 51}, {&maus_s150_eye_21_1, 12, 56}, {&maus_s150_eye_21_2, 12, 62}, {&maus_s150_eye_21_3, 12, 65}},
  {{&maus_s150_eye_22_0, 13, 61}, {&maus_s150_eye_22_1, 13, 63}, {&maus_s150_eye_22_2, 13, 65}, {&maus_s150_eye_22_3, 13, 66}},
};

static const maus_layer_t mouth[MAUS_EXPR_COUNT] = {
  {&maus_s150_mouth_0, 38, 87},
  {&maus_s150_mouth_1, 40, 91},
  {&maus_s150_mouth_3, 42, 89},
  {&maus_s150_mouth_4, 30, 83},
  {&maus_s150_mouth_5, 38, 92},
  {&maus_s150_mouth_6, 32, 86},
  {&maus_s150_mouth_7, 35, 89},
  {&maus_s150_mouth_8, 28, 90},
  {&maus_s150_mouth_10, 28, 91},
  {&maus_s150_mouth_11, 38, 94},
  {&maus_s150_mouth_13, 36, 83},
  {&maus_s150_mouth_14, 29, 93},
  {&maus_s150_mouth_15, 39, 86},
  {&maus_s150_mouth_16, 26, 89},
  {&maus_s150_mouth_17, 36, 88},
  {&maus_s150_mouth_19, 37, 92},
  {&maus_s150_mouth_21, 41, 90},
  {&maus_s150_mouth_22, 30, 83},
};

static const uint8_t speak_expr[MAUS_SPEAK_EXPRS] = {15, 5};

static const maus_layer_t speak[MAUS_SPEAK_EXPRS][MAUS_SPEAK_LEVELS] = {
  {{&maus_s150_speak_19_1, 37, 91}, {&maus_s150_speak_19_2, 36, 91}, {&maus_s150_speak_19_3, 35, 91}},
  {{&maus_s150_speak_6_1, 31, 86}, {&maus_s150_speak_6_2, 30, 86}, {&maus_s150_speak_6_3, 30, 86}},
};

static const uint8_t pool_idle[] = {5, 0, 7};
static const uint8_t pool_listening[] = {1, 8, 15};
static const uint8_t pool_thinking[] = {14, 7, 13, 11, 4};
static const uint8_t pool_working[] = {8, 6, 13, 9};
static const uint8_t pool_speaking[] = {15, 5};
static const uint8_t pool_sleeping[] = {17, 10, 3};
static const uint8_t pool_curious[] = {16, 2, 0, 12};
static const uint8_t pool_notifying[] = {16, 2, 0};
static const uint8_t pool_alerting[] = {16, 2};

/* pool, pool_len, cadence ms, blink ms (0 = never), bob/jitter/circle: amplitude in 0.1 px, period ms */
static const maus_state_def_t states[UI_MAUS__COUNT] = {
  [UI_MAUS_IDLE] = {pool_idle, 3, 9000, 16000, 6000, 14000, 11, 3600, 0, 0, 0, 0},
  [UI_MAUS_LISTENING] = {pool_listening, 3, 2800, 5000, 3000, 7000, 22, 2600, 0, 0, 0, 0},
  [UI_MAUS_THINKING] = {pool_thinking, 5, 2000, 3600, 3500, 7000, 8, 3000, 0, 0, 0, 0},
  [UI_MAUS_WORKING] = {pool_working, 4, 1800, 3200, 2800, 5500, 16, 900, 0, 0, 0, 0},
  [UI_MAUS_SPEAKING] = {pool_speaking, 2, 3000, 6000, 2500, 5000, 10, 1800, 0, 0, 0, 0},
  [UI_MAUS_SLEEPING] = {pool_sleeping, 3, 6000, 10000, 0, 0, 21, 4600, 0, 0, 0, 0},
  [UI_MAUS_CURIOUS] = {pool_curious, 4, 1800, 3200, 2500, 5500, 0, 0, 0, 0, 0, 0},
  [UI_MAUS_NOTIFYING] = {pool_notifying, 3, 1500, 2600, 2000, 4000, 26, 700, 0, 0, 0, 0},
  [UI_MAUS_ALERTING] = {pool_alerting, 2, 2000, 3600, 0, 0, 0, 0, 17, 85, 0, 0},
};

const maus_art_t maus_art_s150 = {
  .profile = "s150",
  .w = 125,
  .h = 150,
  .body = &maus_s150_body,
  .expr_ids = expr_ids,
  .eyes = eyes,
  .mouth = mouth,
  .speak_expr = speak_expr,
  .speak = speak,
  .states = states,
  .total_bytes = 140260,
};
