/* SPDX-License-Identifier: Apache-2.0 */
/* GENERATED by tools/art (npm run fonts). Do not edit. */
#ifndef UI_FONTS_H
#define UI_FONTS_H

#include "lvgl.h"

LV_FONT_DECLARE(font_latin1_14)
LV_FONT_DECLARE(font_latin1_16)
LV_FONT_DECLARE(font_latin1_20)
LV_FONT_DECLARE(font_latin1_24)
LV_FONT_DECLARE(font_latin1_28)
LV_FONT_DECLARE(font_latin1_40)

#endif /* UI_FONTS_H */
