// SPDX-License-Identifier: Apache-2.0
// npm run fonts [-- --ttf <Montserrat-Medium.ttf>]
// Latin-1 (+ U+2026, U+2192) bitmap fonts for LVGL from Montserrat Medium (OFL-1.1),
// with the locked lv_font_conv 1.5.3. Writes firmware/ui/fonts/font_latin1_<px>.c
// and firmware/ui/fonts/ui_fonts.h. The TTF is --ttf, else the copy in a
// configured build tree (build/host or build/snap), else LVGL v9.6.0's own file
// downloaded from GitHub; whichever it is must have the pinned SHA-256.
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export const SIZES = [14, 16, 20, 24, 28, 40]
const RANGES = '0x20-0x7E,0xA0-0xFF,0x2026,0x2192'
// SHA-256 of scripts/generators/built_in_font/Montserrat-Medium.ttf in LVGL v9.6.0.
const TTF_SHA256 = '421f26b23e2be6b98373d32acd3cb2897b154d4bf0a77d26534ce476e4cbed53'
const TTF_URL = 'https://raw.githubusercontent.com/lvgl/lvgl/v9.6.0/scripts/generators/built_in_font/Montserrat-Medium.ttf'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..', '..')
const FONTS = join(ROOT, 'firmware', 'ui', 'fonts')
const CONV = join(HERE, 'node_modules', '.bin', 'lv_font_conv')
const CANDIDATES = ['build/host', 'build/snap'].map(b =>
  join(ROOT, b, '_deps', 'lvgl-src', 'scripts', 'generators', 'built_in_font', 'Montserrat-Medium.ttf'))

async function loadTtf(): Promise<{ from: string; bytes: Buffer }> {
  const i = process.argv.indexOf('--ttf')
  if (i >= 0) {
    const path = resolve(process.argv[i + 1])
    return { from: path, bytes: readFileSync(path) }
  }
  const found = CANDIDATES.find(p => existsSync(p))
  if (found) return { from: found, bytes: readFileSync(found) }
  console.log(`no configured build tree: downloading ${TTF_URL}`)
  try {
    const res = await fetch(TTF_URL)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    return { from: TTF_URL, bytes: Buffer.from(await res.arrayBuffer()) }
  } catch (e) {
    console.error(`Montserrat-Medium.ttf: download failed (${(e as Error).message}). Configure the desktop build ` +
      'first (cmake -S firmware -B build/host), or pass --ttf <path to LVGL 9.6.0 Montserrat-Medium.ttf>.')
    process.exit(2)
  }
}

const ttf = await loadTtf()
const sha = createHash('sha256').update(ttf.bytes).digest('hex')
if (sha !== TTF_SHA256) {
  console.error(`${ttf.from}: SHA-256 ${sha} is not LVGL 9.6.0's Montserrat-Medium.ttf (${TTF_SHA256})`)
  process.exit(1)
}

// Relative arguments only, so the "Opts:" line lv_font_conv writes into each
// file is identical on every machine.
const work = mkdtempSync(join(tmpdir(), 'omb-fonts-'))
try {
  writeFileSync(join(work, 'Montserrat-Medium.ttf'), ttf.bytes)
  mkdirSync(FONTS, { recursive: true })
  for (const px of SIZES) {
    const out = `font_latin1_${px}.c`
    execFileSync(CONV, ['--font', 'Montserrat-Medium.ttf', '-r', RANGES, '--size', String(px), '--bpp', '4',
      '--format', 'lvgl', '--no-compress', '--lv-include', 'lvgl.h', '-o', out], { cwd: work, stdio: 'inherit' })
    const body = readFileSync(join(work, out), 'utf8')
    writeFileSync(join(FONTS, out),
      '/* SPDX-License-Identifier: OFL-1.1 */\n' +
      '/* GENERATED by tools/art (npm run fonts) from Montserrat Medium (SIL Open Font\n' +
      ' * License 1.1, shipped with LVGL 9.6.0) with lv_font_conv 1.5.3. Do not edit. */\n' + body)
    console.log(`wrote firmware/ui/fonts/${out}`)
  }
} finally {
  rmSync(work, { recursive: true, force: true })
}

writeFileSync(join(FONTS, 'ui_fonts.h'),
  '/* SPDX-License-Identifier: Apache-2.0 */\n' +
  '/* GENERATED by tools/art (npm run fonts). Do not edit. */\n' +
  '#ifndef UI_FONTS_H\n#define UI_FONTS_H\n\n#include "lvgl.h"\n\n' +
  SIZES.map(px => `LV_FONT_DECLARE(font_latin1_${px})`).join('\n') + '\n\n#endif /* UI_FONTS_H */\n')
console.log('wrote firmware/ui/fonts/ui_fonts.h')
