// SPDX-License-Identifier: Apache-2.0
// RGBA (straight alpha) -> LVGL 9 image data, and the C text for it.
//
// RGB565A8 (LVGL 9 layout): the whole RGB565 plane first (little-endian
// uint16 per pixel, stride w*2), then the whole A8 plane (stride w).
// A8: one alpha byte per pixel; LVGL draws it in the image_recolor colour.

export interface Rgba {
  width: number
  height: number
  data: Uint8Array        // straight (not premultiplied) RGBA, row-major
}
export type ColorFormat = 'RGB565A8' | 'A8'
export interface LvImage {
  name: string
  cf: ColorFormat
  w: number
  h: number
  stride: number
  data: Uint8Array
}
export interface Trimmed {
  image: Rgba
  x: number
  y: number
}

const BAYER4 = [0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5]

/** Crop to the bounding box of alpha > 0. A fully transparent input is an error. */
export function trim(src: Rgba): Trimmed {
  let x0 = src.width, y0 = src.height, x1 = -1, y1 = -1
  for (let y = 0; y < src.height; y++) {
    for (let x = 0; x < src.width; x++) {
      if (src.data[(y * src.width + x) * 4 + 3] !== 0) {
        if (x < x0) x0 = x
        if (x > x1) x1 = x
        if (y < y0) y0 = y
        if (y > y1) y1 = y
      }
    }
  }
  if (x1 < 0) throw new Error('trim: layer is fully transparent')
  const w = x1 - x0 + 1
  const h = y1 - y0 + 1
  const data = new Uint8Array(w * h * 4)
  for (let y = 0; y < h; y++) {
    const from = ((y0 + y) * src.width + x0) * 4
    data.set(src.data.subarray(from, from + w * 4), y * w * 4)
  }
  return { image: { width: w, height: h, data }, x: x0, y: y0 }
}

/** RGB565 with a 4x4 ordered dither: bias 0..step-1 before truncation. Transparent pixels are 0. */
export function rgb565(r: number, g: number, b: number, x: number, y: number): number {
  const t = BAYER4[(y & 3) * 4 + (x & 3)]
  const r5 = Math.min(31, (r + (t >> 1)) >> 3)
  const g6 = Math.min(63, (g + (t >> 2)) >> 2)
  const b5 = Math.min(31, (b + (t >> 1)) >> 3)
  return (r5 << 11) | (g6 << 5) | b5
}

export function toLvImage(name: string, src: Rgba, cf: ColorFormat): LvImage {
  const { width: w, height: h, data } = src
  if (cf === 'A8') {
    const out = new Uint8Array(w * h)
    for (let i = 0; i < w * h; i++) out[i] = data[i * 4 + 3]
    return { name, cf, w, h, stride: w, data: out }
  }
  const out = new Uint8Array(w * h * 3)
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const i = y * w + x
      const a = data[i * 4 + 3]
      const c = a === 0 ? 0 : rgb565(data[i * 4], data[i * 4 + 1], data[i * 4 + 2], x, y)
      out[i * 2] = c & 0xff
      out[i * 2 + 1] = c >> 8
      out[w * h * 2 + i] = a
    }
  }
  return { name, cf, w, h, stride: w * 2, data: out }
}

export function cBytes(data: Uint8Array): string {
  const lines: string[] = []
  for (let i = 0; i < data.length; i += 24) {
    lines.push('  ' + Array.from(data.subarray(i, i + 24), v => '0x' + v.toString(16).padStart(2, '0')).join(','))
  }
  return lines.join(',\n')
}

/** One image as C: a static byte array plus a public lv_image_dsc_t. */
export function cImage(img: LvImage): string {
  return `static const LV_ATTRIBUTE_MEM_ALIGN uint8_t ${img.name}_map[] = {\n${cBytes(img.data)}\n};\n\n` +
    `const lv_image_dsc_t ${img.name} = {\n` +
    `  .header = {\n` +
    `    .magic = LV_IMAGE_HEADER_MAGIC,\n` +
    `    .cf = LV_COLOR_FORMAT_${img.cf},\n` +
    `    .flags = 0,\n` +
    `    .w = ${img.w},\n` +
    `    .h = ${img.h},\n` +
    `    .stride = ${img.stride},\n` +
    `  },\n` +
    `  .data_size = sizeof(${img.name}_map),\n` +
    `  .data = ${img.name}_map,\n` +
    `};\n`
}

export const C_HEADER = '/* SPDX-License-Identifier: Apache-2.0 */\n' +
  '/* GENERATED by tools/art (npm run art). Do not edit.\n' +
  ' * Geometry: OpenMausBot (Apache-2.0); see tools/art/source/README.md. */\n'
