/* SPDX-License-Identifier: Apache-2.0 */
/* GENERATED by tools/art (npm run art). Do not edit.
 * Geometry: OpenMausBot (Apache-2.0); see tools/art/source/README.md. */
#include "maus_art.h"

extern const lv_image_dsc_t maus_s240_body;
extern const lv_image_dsc_t maus_s240_eye_0_0;
extern const lv_image_dsc_t maus_s240_eye_0_1;
extern const lv_image_dsc_t maus_s240_eye_0_2;
extern const lv_image_dsc_t maus_s240_eye_0_3;
extern const lv_image_dsc_t maus_s240_eye_1_0;
extern const lv_image_dsc_t maus_s240_eye_1_1;
extern const lv_image_dsc_t maus_s240_eye_1_2;
extern const lv_image_dsc_t maus_s240_eye_1_3;
extern const lv_image_dsc_t maus_s240_eye_3_0;
extern const lv_image_dsc_t maus_s240_eye_3_1;
extern const lv_image_dsc_t maus_s240_eye_3_2;
extern const lv_image_dsc_t maus_s240_eye_3_3;
extern const lv_image_dsc_t maus_s240_eye_4_0;
extern const lv_image_dsc_t maus_s240_eye_4_1;
extern const lv_image_dsc_t maus_s240_eye_4_2;
extern const lv_image_dsc_t maus_s240_eye_4_3;
extern const lv_image_dsc_t maus_s240_eye_5_0;
extern const lv_image_dsc_t maus_s240_eye_5_1;
extern const lv_image_dsc_t maus_s240_eye_5_2;
extern const lv_image_dsc_t maus_s240_eye_5_3;
extern const lv_image_dsc_t maus_s240_eye_6_0;
extern const lv_image_dsc_t maus_s240_eye_6_1;
extern const lv_image_dsc_t maus_s240_eye_6_2;
extern const lv_image_dsc_t maus_s240_eye_6_3;
extern const lv_image_dsc_t maus_s240_eye_7_0;
extern const lv_image_dsc_t maus_s240_eye_7_1;
extern const lv_image_dsc_t maus_s240_eye_7_2;
extern const lv_image_dsc_t maus_s240_eye_7_3;
extern const lv_image_dsc_t maus_s240_eye_8_0;
extern const lv_image_dsc_t maus_s240_eye_8_1;
extern const lv_image_dsc_t maus_s240_eye_8_2;
extern const lv_image_dsc_t maus_s240_eye_8_3;
extern const lv_image_dsc_t maus_s240_eye_10_0;
extern const lv_image_dsc_t maus_s240_eye_10_1;
extern const lv_image_dsc_t maus_s240_eye_10_2;
extern const lv_image_dsc_t maus_s240_eye_10_3;
extern const lv_image_dsc_t maus_s240_eye_11_0;
extern const lv_image_dsc_t maus_s240_eye_11_1;
extern const lv_image_dsc_t maus_s240_eye_11_2;
extern const lv_image_dsc_t maus_s240_eye_11_3;
extern const lv_image_dsc_t maus_s240_eye_13_0;
extern const lv_image_dsc_t maus_s240_eye_13_1;
extern const lv_image_dsc_t maus_s240_eye_13_2;
extern const lv_image_dsc_t maus_s240_eye_13_3;
extern const lv_image_dsc_t maus_s240_eye_14_0;
extern const lv_image_dsc_t maus_s240_eye_14_1;
extern const lv_image_dsc_t maus_s240_eye_14_2;
extern const lv_image_dsc_t maus_s240_eye_14_3;
extern const lv_image_dsc_t maus_s240_eye_15_0;
extern const lv_image_dsc_t maus_s240_eye_15_1;
extern const lv_image_dsc_t maus_s240_eye_15_2;
extern const lv_image_dsc_t maus_s240_eye_15_3;
extern const lv_image_dsc_t maus_s240_eye_16_0;
extern const lv_image_dsc_t maus_s240_eye_16_1;
extern const lv_image_dsc_t maus_s240_eye_16_2;
extern const lv_image_dsc_t maus_s240_eye_16_3;
extern const lv_image_dsc_t maus_s240_eye_17_0;
extern const lv_image_dsc_t maus_s240_eye_17_1;
extern const lv_image_dsc_t maus_s240_eye_17_2;
extern const lv_image_dsc_t maus_s240_eye_17_3;
extern const lv_image_dsc_t maus_s240_eye_19_0;
extern const lv_image_dsc_t maus_s240_eye_19_1;
extern const lv_image_dsc_t maus_s240_eye_19_2;
extern const lv_image_dsc_t maus_s240_eye_19_3;
extern const lv_image_dsc_t maus_s240_eye_21_0;
extern const lv_image_dsc_t maus_s240_eye_21_1;
extern const lv_image_dsc_t maus_s240_eye_21_2;
extern const lv_image_dsc_t maus_s240_eye_21_3;
extern const lv_image_dsc_t maus_s240_eye_22_0;
extern const lv_image_dsc_t maus_s240_eye_22_1;
extern const lv_image_dsc_t maus_s240_eye_22_2;
extern const lv_image_dsc_t maus_s240_eye_22_3;
extern const lv_image_dsc_t maus_s240_mouth_0;
extern const lv_image_dsc_t maus_s240_mouth_1;
extern const lv_image_dsc_t maus_s240_mouth_3;
extern const lv_image_dsc_t maus_s240_mouth_4;
extern const lv_image_dsc_t maus_s240_mouth_5;
extern const lv_image_dsc_t maus_s240_mouth_6;
extern const lv_image_dsc_t maus_s240_mouth_7;
extern const lv_image_dsc_t maus_s240_mouth_8;
extern const lv_image_dsc_t maus_s240_mouth_10;
extern const lv_image_dsc_t maus_s240_mouth_11;
extern const lv_image_dsc_t maus_s240_mouth_13;
extern const lv_image_dsc_t maus_s240_mouth_14;
extern const lv_image_dsc_t maus_s240_mouth_15;
extern const lv_image_dsc_t maus_s240_mouth_16;
extern const lv_image_dsc_t maus_s240_mouth_17;
extern const lv_image_dsc_t maus_s240_mouth_19;
extern const lv_image_dsc_t maus_s240_mouth_21;
extern const lv_image_dsc_t maus_s240_mouth_22;
extern const lv_image_dsc_t maus_s240_speak_19_1;
extern const lv_image_dsc_t maus_s240_speak_19_2;
extern const lv_image_dsc_t maus_s240_speak_19_3;
extern const lv_image_dsc_t maus_s240_speak_6_1;
extern const lv_image_dsc_t maus_s240_speak_6_2;
extern const lv_image_dsc_t maus_s240_speak_6_3;

static const uint8_t expr_ids[MAUS_EXPR_COUNT] = {0, 1, 3, 4, 5, 6, 7, 8, 10, 11, 13, 14, 15, 16, 17, 19, 21, 22};

static const maus_layer_t eyes[MAUS_EXPR_COUNT][MAUS_BLINK_STEPS] = {
  {{&maus_s240_eye_0_0, 36, 91}, {&maus_s240_eye_0_1, 36, 97}, {&maus_s240_eye_0_2, 36, 103}, {&maus_s240_eye_0_3, 37, 107}},
  {{&maus_s240_eye_1_0, 32, 82}, {&maus_s240_eye_1_1, 32, 92}, {&maus_s240_eye_1_2, 32, 100}, {&maus_s240_eye_1_3, 32, 106}},
  {{&maus_s240_eye_3_0, 23, 80}, {&maus_s240_eye_3_1, 23, 89}, {&maus_s240_eye_3_2, 23, 97}, {&maus_s240_eye_3_3, 23, 102}},
  {{&maus_s240_eye_4_0, 21, 97}, {&maus_s240_eye_4_1, 21, 100}, {&maus_s240_eye_4_2, 21, 104}, {&maus_s240_eye_4_3, 21, 106}},
  {{&maus_s240_eye_5_0, 30, 91}, {&maus_s240_eye_5_1, 30, 100}, {&maus_s240_eye_5_2, 30, 104}, {&maus_s240_eye_5_3, 30, 106}},
  {{&maus_s240_eye_6_0, 37, 92}, {&maus_s240_eye_6_1, 37, 98}, {&maus_s240_eye_6_2, 37, 104}, {&maus_s240_eye_6_3, 37, 107}},
  {{&maus_s240_eye_7_0, 27, 85}, {&maus_s240_eye_7_1, 27, 94}, {&maus_s240_eye_7_2, 27, 103}, {&maus_s240_eye_7_3, 27, 108}},
  {{&maus_s240_eye_8_0, 32, 86}, {&maus_s240_eye_8_1, 32, 94}, {&maus_s240_eye_8_2, 32, 101}, {&maus_s240_eye_8_3, 32, 105}},
  {{&maus_s240_eye_10_0, 32, 80}, {&maus_s240_eye_10_1, 32, 90}, {&maus_s240_eye_10_2, 32, 99}, {&maus_s240_eye_10_3, 32, 105}},
  {{&maus_s240_eye_11_0, 24, 66}, {&maus_s240_eye_11_1, 24, 81}, {&maus_s240_eye_11_2, 24, 94}, {&maus_s240_eye_11_3, 24, 102}},
  {{&maus_s240_eye_13_0, 23, 97}, {&maus_s240_eye_13_1, 23, 100}, {&maus_s240_eye_13_2, 23, 104}, {&maus_s240_eye_13_3, 23, 106}},
  {{&maus_s240_eye_14_0, 30, 80}, {&maus_s240_eye_14_1, 30, 90}, {&maus_s240_eye_14_2, 30, 100}, {&maus_s240_eye_14_3, 30, 105}},
  {{&maus_s240_eye_15_0, 44, 92}, {&maus_s240_eye_15_1, 44, 99}, {&maus_s240_eye_15_2, 44, 104}, {&maus_s240_eye_15_3, 44, 108}},
  {{&maus_s240_eye_16_0, 37, 80}, {&maus_s240_eye_16_1, 37, 90}, {&maus_s240_eye_16_2, 37, 99}, {&maus_s240_eye_16_3, 37, 104}},
  {{&maus_s240_eye_17_0, 34, 86}, {&maus_s240_eye_17_1, 34, 94}, {&maus_s240_eye_17_2, 34, 101}, {&maus_s240_eye_17_3, 34, 105}},
  {{&maus_s240_eye_19_0, 33, 82}, {&maus_s240_eye_19_1, 33, 92}, {&maus_s240_eye_19_2, 33, 101}, {&maus_s240_eye_19_3, 34, 106}},
  {{&maus_s240_eye_21_0, 20, 81}, {&maus_s240_eye_21_1, 20, 91}, {&maus_s240_eye_21_2, 20, 99}, {&maus_s240_eye_21_3, 20, 104}},
  {{&maus_s240_eye_22_0, 21, 98}, {&maus_s240_eye_22_1, 21, 101}, {&maus_s240_eye_22_2, 21, 104}, {&maus_s240_eye_22_3, 21, 106}},
};

static const maus_layer_t mouth[MAUS_EXPR_COUNT] = {
  {&maus_s240_mouth_0, 62, 139},
  {&maus_s240_mouth_1, 64, 146},
  {&maus_s240_mouth_3, 68, 143},
  {&maus_s240_mouth_4, 48, 132},
  {&maus_s240_mouth_5, 62, 147},
  {&maus_s240_mouth_6, 52, 139},
  {&maus_s240_mouth_7, 57, 143},
  {&maus_s240_mouth_8, 45, 143},
  {&maus_s240_mouth_10, 46, 146},
  {&maus_s240_mouth_11, 62, 150},
  {&maus_s240_mouth_13, 59, 133},
  {&maus_s240_mouth_14, 46, 149},
  {&maus_s240_mouth_15, 63, 138},
  {&maus_s240_mouth_16, 43, 143},
  {&maus_s240_mouth_17, 59, 141},
  {&maus_s240_mouth_19, 60, 147},
  {&maus_s240_mouth_21, 65, 143},
  {&maus_s240_mouth_22, 48, 133},
};

static const uint8_t speak_expr[MAUS_SPEAK_EXPRS] = {15, 5};

static const maus_layer_t speak[MAUS_SPEAK_EXPRS][MAUS_SPEAK_LEVELS] = {
  {{&maus_s240_speak_19_1, 59, 146}, {&maus_s240_speak_19_2, 58, 146}, {&maus_s240_speak_19_3, 57, 146}},
  {{&maus_s240_speak_6_1, 50, 138}, {&maus_s240_speak_6_2, 49, 138}, {&maus_s240_speak_6_3, 48, 138}},
};

static const uint8_t pool_idle[] = {5, 0, 7};
static const uint8_t pool_listening[] = {1, 8, 15};
static const uint8_t pool_thinking[] = {14, 7, 13, 11, 4};
static const uint8_t pool_working[] = {8, 6, 13, 9};
static const uint8_t pool_speaking[] = {15, 5};
static const uint8_t pool_sleeping[] = {17, 10, 3};
static const uint8_t pool_curious[] = {16, 2, 0, 12};
static const uint8_t pool_notifying[] = {16, 2, 0};
static const uint8_t pool_alerting[] = {16, 2};

/* pool, pool_len, cadence ms, blink ms (0 = never), bob/jitter/circle: amplitude in 0.1 px, period ms */
static const maus_state_def_t states[UI_MAUS__COUNT] = {
  [UI_MAUS_IDLE] = {pool_idle, 3, 9000, 16000, 6000, 14000, 17, 3600, 0, 0, 0, 0},
  [UI_MAUS_LISTENING] = {pool_listening, 3, 2800, 5000, 3000, 7000, 35, 2600, 0, 0, 0, 0},
  [UI_MAUS_THINKING] = {pool_thinking, 5, 2000, 3600, 3500, 7000, 12, 3000, 0, 0, 0, 0},
  [UI_MAUS_WORKING] = {pool_working, 4, 1800, 3200, 2800, 5500, 26, 900, 0, 0, 0, 0},
  [UI_MAUS_SPEAKING] = {pool_speaking, 2, 3000, 6000, 2500, 5000, 16, 1800, 0, 0, 0, 0},
  [UI_MAUS_SLEEPING] = {pool_sleeping, 3, 6000, 10000, 0, 0, 34, 4600, 0, 0, 0, 0},
  [UI_MAUS_CURIOUS] = {pool_curious, 4, 1800, 3200, 2500, 5500, 0, 0, 0, 0, 0, 0},
  [UI_MAUS_NOTIFYING] = {pool_notifying, 3, 1500, 2600, 2000, 4000, 42, 700, 0, 0, 0, 0},
  [UI_MAUS_ALERTING] = {pool_alerting, 2, 2000, 3600, 0, 0, 0, 0, 27, 85, 0, 0},
};

const maus_art_t maus_art_s240 = {
  .profile = "s240",
  .w = 201,
  .h = 240,
  .body = &maus_s240_body,
  .expr_ids = expr_ids,
  .eyes = eyes,
  .mouth = mouth,
  .speak_expr = speak_expr,
  .speak = speak,
  .states = states,
  .total_bytes = 356786,
};
