/* firmware/ui/art/maus_art.h (generated) */
/* SPDX-License-Identifier: Apache-2.0 */
/* GENERATED by tools/art (npm run art). Do not edit.
 * Layered Maus art (spec §5.5): one RGB565A8 body per profile, A8 eye
 * frames per expression x 4 blink steps, RGB565A8 closed mouths, RGB565A8
 * open mouths for the gadget-only speaking state; offsets are relative to
 * the body's top-left corner. */
#ifndef MAUS_ART_H
#define MAUS_ART_H

#include "lvgl.h"
#include "gadget_board.h"
#include "gadget_ui_model.h"

#define MAUS_EXPR_COUNT 18      /* union of the state pools in tools/art/source/states.json */
#define MAUS_BLINK_STEPS 4      /* eye openness 1.0, 0.6, 0.25, 0.04 */
#define MAUS_SPEAK_EXPRS 2      /* expressions with open mouths: 19, 6 */
#define MAUS_SPEAK_LEVELS 3     /* open-mouth levels 1..3 (level 0 = the closed mouth) */

typedef struct {
  const lv_image_dsc_t *img;
  int16_t x, y;
} maus_layer_t;

typedef struct {
  const uint8_t *pool;            /* indexes into expr_ids */
  uint8_t pool_len;
  uint16_t cad_min_ms, cad_max_ms;      /* time between expression changes */
  uint16_t blink_min_ms, blink_max_ms;  /* 0, 0 = never blinks */
  int16_t bob_px_x10;  uint16_t bob_ms;     /* translation only (v1); amplitudes in 0.1 px */
  int16_t jitter_px_x10; uint16_t jitter_ms;
  int16_t circle_px_x10; uint16_t circle_ms;
} maus_state_def_t;

typedef struct {
  const char *profile;                                   /* "s240" | "s150" */
  uint16_t w, h;                                         /* body size: 201x240 | 125x150 */
  const lv_image_dsc_t *body;
  const uint8_t *expr_ids;                               /* [MAUS_EXPR_COUNT] app expression numbers */
  const maus_layer_t (*eyes)[MAUS_BLINK_STEPS];          /* [MAUS_EXPR_COUNT][MAUS_BLINK_STEPS] */
  const maus_layer_t *mouth;                             /* [MAUS_EXPR_COUNT] */
  const uint8_t *speak_expr;                             /* [MAUS_SPEAK_EXPRS] indexes into expr_ids */
  const maus_layer_t (*speak)[MAUS_SPEAK_LEVELS];        /* [MAUS_SPEAK_EXPRS][MAUS_SPEAK_LEVELS] */
  const maus_state_def_t *states;                        /* [UI_MAUS__COUNT]; [UI_MAUS_NONE] unused */
  uint32_t total_bytes;                                  /* sum of every image's data_size (budget check) */
} maus_art_t;

/* Simulator links both profiles; an ESP32 build links only its board's. */
extern const maus_art_t maus_art_s240;
extern const maus_art_t maus_art_s150;
/* NULL when that profile is not linked into this build. */
const maus_art_t *maus_art_for(gadget_art_profile_t profile);

#endif /* MAUS_ART_H */
