/* SPDX-License-Identifier: Apache-2.0 */
/* GENERATED by tools/art (npm run art). Do not edit.
 * Geometry: OpenMausBot (Apache-2.0); see tools/art/source/README.md. */
#include "maus_art.h"

/* MAUS_ART_HAS_S240 / MAUS_ART_HAS_S150 come from firmware/ui/CMakeLists.txt:
 * the desktop build links both profiles, an ESP32 build only its board's. */
const maus_art_t *maus_art_for(gadget_art_profile_t profile) {
  switch (profile) {
#if defined(MAUS_ART_HAS_S240)
  case GADGET_ART_S240:
    return &maus_art_s240;
#endif
#if defined(MAUS_ART_HAS_S150)
  case GADGET_ART_S150:
    return &maus_art_s150;
#endif
  default:
    return NULL;
  }
}
